apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: cypress-github-action-test-location
  description: Links to additional entities in the cypress-github-action-test repository.
  annotations:
    github.com/project-slug: Bandwidth/cypress-github-action-test
spec:
  targets:
    - ./component.yaml
